apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: belloga-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "af13e25e0bf784b9d980f772393690ae-912693386.ap-northeast-2.elb.amazonaws.com" # istio gateway 경로
    - "api.belloga.com" # api endpoint
    - "grafana.belloga.com" # grafana
--- # 그라파나용 게이트웨이
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: belloga-grafana
spec:
  hosts:
  - "grafana.belloga.com" # grafana endpoint
  gateways:
  - belloga-gateway
  http:

  - match:
    - uri:
        prefix: /kiali
    route:
    - destination:
        host: kiali.istio-system.svc.cluster.local
        port:
          number: 20001

  - match:
    - uri:
        prefix: /jaeger
    route:
    - destination:
        host: tracing.istio-system.svc.cluster.local
        port:
          number: 80

  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: grafana.istio-system.svc.cluster.local
        port:
          number: 3000
--- # api gateway
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: belloga-api
spec:
  hosts:
  - "af13e25e0bf784b9d980f772393690ae-912693386.ap-northeast-2.elb.amazonaws.com" # istio gateway 경로
  - "api.belloga.com" # api endpoint
  #- "*"
  gateways:
  - belloga-gateway
  http:
  - match:
    - uri:
        prefix: /api/user
    route:
    - destination:
        host: user-service
        port:
          number: 8080

  - match:
    - uri:
        prefix: /api/data
    - uri:
        prefix: /api/labeled-data
    - uri:
        prefix: /api/labeled-result
    route:
    - destination:
        host: labeling-service
        port:
          number: 8080

  - match:
    - uri:
        prefix: /api/account
    route:
    - destination:
        host: auth-service
        port:
          number: 8080

  - match:
    - uri:
        prefix: /api/point
    - uri:
        prefix: /api/stemp
    - uri:
        prefix: /api/temp-point
    route:
    - destination:
        host: point-service
        port:
          number: 8080

  - match:
    - uri:
        prefix: /api/raw-data
    route:
    - destination:
        host: raw-data-service
        port:
          number: 8080
