# https://nangman14.tistory.com/60
# https://intrepidgeeks.com/tutorial/istio-service-entry
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-star-aws-services-https
spec:
  hosts:
    - "*.ap-northeast-2.amazonaws.com"
    - "*.ap-northeast-2.rds.amazonaws.com"
    - "openapi.naver.com"
    - "*.google.com"
  location: MESH_EXTERNAL
  ports:
    - number: 80
      name: http
      protocol: HTTP
    - number: 443
      name: tls
      protocol: TLS

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-star-aws-services-https
spec:
  hosts:
    - "*.ap-northeast-2.amazonaws.com"
  tls:
    - match:
        - port: 443
          sniHosts:
            - "*.ap-northeast-2.amazonaws.com"
      route:
        - destination:
            host: "*.ap-northeast-2.amazonaws.com"
            port:
              number: 443
