apiVersion: v1
kind: Service
metadata:
  name: labeling-service
  labels:
    app: labeling-service
    service: labeling-service
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: labeling-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: belloga-labeling-service
  labels:
    account: labeling-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: labeling-service-v1
  labels:
    app: labeling-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labeling-service
      version: v1
  template:
    metadata:
      labels:
        app: labeling-service
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
        traffic.sidecar.istio.io/excludeInboundPorts: "9092,3306" # 9092,3306 카프카포트는 istio proxy 처리에서 제외하겠다.
        traffic.sidecar.istio.io/excludeOutboundPorts: "9092,3306"

    spec:
      serviceAccountName: belloga-labeling-service
      containers:
        - name: labeling-service
          image: 023778162658.dkr.ecr.ap-northeast-2.amazonaws.com/belloga-labeling-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
