apiVersion: v1
kind: Service
metadata:
  name: admin-frontend
  labels:
    app: admin-frontend
    service: admin-frontend
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: admin-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: belloga-admin-frontend
  labels:
    account: admin-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend-v1
  labels:
    app: admin-frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-frontend
      version: v1
  template:
    metadata:
      labels:
        app: admin-frontend
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
        traffic.sidecar.istio.io/excludeInboundPorts: "9092"
        traffic.sidecar.istio.io/excludeOutboundPorts: "9092"
    spec:
      serviceAccountName: belloga-admin-frontend
      containers:
        - name: admin-frontend
          image: 023778162658.dkr.ecr.ap-northeast-2.amazonaws.com/belloga-admin-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
